### ISSUE TITLE
truncated ma table data breaks refpix and darkcurrent

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1022]
_Issue [RCAL-721](https://jira.stsci.edu/browse/RCAL-721) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Using truncated data provided by RTB, the refpix and darkcurrent step break.

The data is

█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

When run as

strun roman_elp r0000101001001001001_01101_0003_WFI01_uncal.asdf

The following occurs for refpix

2023-11-21 10:24:15,702 - stpipe.ExposurePipeline.refpix - INFO - Step refpix running with args (<roman_datamodels.datamodels._datamodels.RampModel object at 0x29548c050>,).
2023-11-21 10:24:15,702 - stpipe.ExposurePipeline.refpix - INFO - Step refpix parameters are: \{'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.asdf', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'remove_offset': True, 'remove_trends': True, 'cosine_interpolate': True, 'fft_interpolate': False}
----------------------------------------------------------------------
ERROR RUNNING STEP 'ExposurePipeline':
    all the input array dimensions except for the concatenation axis
    must match exactly, but along dimension 0, the array at index 0
    has size 6 and the array at index 1 has size 10
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/cli/strun.py", line 24, in main
    Step.from_cmdline(sys.argv[1:])
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/step.py", line 187, in from_cmdline
    return cmdline.step_from_cmdline(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/cmdline.py", line 392, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/step.py", line 479, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/Documents/ssbdev/romancal_project/rcaltesting_romancal/romancal/pipeline/exposure_pipeline.py", line 148, in process
    result = self.refpix(result)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/step.py", line 479, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/Documents/ssbdev/romancal_project/rcaltesting_romancal/romancal/refpix/refpix_step.py", line 49, in process
    output = refpix.run_steps(
             ^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/Documents/ssbdev/romancal_project/rcaltesting_romancal/romancal/refpix/refpix.py", line 30, in run_steps
    standard = StandardView.from_datamodel(datamodel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/Documents/ssbdev/romancal_project/rcaltesting_romancal/romancal/refpix/data.py", line 107, in from_datamodel
    return cls(np.dstack([detector, amp33]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/numpy/lib/shape_base.py", line 715, in dstack
    return _nx.concatenate(arrs, 2)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 10

 

When skipping refpix, darkcurrent fails as follows

2023-11-21 10:25:18,073 - stpipe.ExposurePipeline.dark_current - INFO - Step dark_current running with args (<roman_datamodels.datamodels._datamodels.RampModel object at 0x280db6150>,).
2023-11-21 10:25:18,074 - stpipe.ExposurePipeline.dark_current - INFO - Step dark_current parameters are: \{'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.asdf', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'dark_output': None}
2023-11-21 10:25:18,075 - stpipe.ExposurePipeline.dark_current - INFO - Using DARK reference file: /Users/eisenham/Downloads/crds-cache/roman_ops/references/roman/wfi/roman_wfi_dark_0896.asdf
----------------------------------------------------------------------
ERROR RUNNING STEP 'ExposurePipeline':
    operands could not be broadcast together with shapes (6,4096,4096)
    (10,4096,4096) (6,4096,4096)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/cli/strun.py", line 24, in main
    Step.from_cmdline(sys.argv[1:])
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/step.py", line 187, in from_cmdline
    return cmdline.step_from_cmdline(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/cmdline.py", line 392, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/step.py", line 479, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/Documents/ssbdev/romancal_project/rcaltesting_romancal/romancal/pipeline/exposure_pipeline.py", line 150, in process
    result = self.dark_current(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/stpipe/step.py", line 479, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/eisenham/Documents/ssbdev/romancal_project/rcaltesting_romancal/romancal/dark_current/dark_current_step.py", line 45, in process
    out_model.data -= dark_model.data
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/astropy/units/quantity.py", line 691, in *_array_ufunc_*
    raise e
  File "/Users/eisenham/miniforge3/envs/rcaltesting/lib/python3.11/site-packages/astropy/units/quantity.py", line 666, in *_array_ufunc_*
    result = super().*_array_ufunc_*(function, method, *arrays, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (6,4096,4096) (10,4096,4096) (6,4096,4096)

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RCAL-721?focusedCommentId=672709#comment-672709):_

There are at least two issues here:
 # In dark current subtraction, we need to truncate to the appropriate number of resultants.
 # In the L1 files, the number of resultants for amp33 need to match the number of resultants for the data array.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Eddie Schlafly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eschlafly) on [JIRA](https://jira.stsci.edu/browse/RCAL-721?focusedCommentId=673290#comment-673290):_

The romancal side of this was addressed in #1023 .  There's an outstanding issue on the L1 generation side to make sure that L1 data & amp33 arrays have the same size.  But there's nothing to do for romancal here, so I am inclined to close.
