### ISSUE TITLE
MosaicModel.append_individual_image_meta crashes when handling numpy.ndarray.

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1234]
_Issue [RCAL-838](https://jira.stsci.edu/browse/RCAL-838) was created on JIRA by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro):_

MosaicModel.append_individual_image_meta checks for keys and values for each attribute in meta. There is a bug in the code that is preventing the proper check of np.NDArray. This is the TB:
```java
Traceback (most recent call last):
  File "/Users/mteodoro/.pyenv/versions/romancal_venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-63bce3236145>", line 1, in <module>
    isinstance(value.strip(), asdf.tags.core.ndarray.NDArrayType)
               ^^^^^^^^^^^
  File "/Users/mteodoro/.pyenv/versions/romancal_venv/lib/python3.11/site-packages/asdf/tags/core/ndarray.py", line 393, in __getattr__
    return getattr(self._make_array(), attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'strip' ```

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) on [JIRA](https://jira.stsci.edu/browse/RCAL-838?focusedCommentId=698522#comment-698522):_

PR for review: spacetelescope/roman_datamodels#350
