### ISSUE TITLE
Update asn_from_list to accept target argument

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1408]
_Issue [RCAL-910](https://jira.stsci.edu/browse/RCAL-910) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Update asn_from_list to accept a command line argument to set the target field.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-910?focusedCommentId=718066#comment-718066):_

Adding this has reveled some additional errors in the association code, 
```java
from romancal.associations.registry import AssociationRegistry
>>> registry = AssociationRegistry()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ddavis/src/Roman/romancal/romancal/associations/registry.py", line 93, in _init_
    self.populate(
  File "/Users/ddavis/src/Roman/romancal/romancal/associations/registry.py", line 267, in populate
    self.Utility = type("Utility", (obj, self.Utility), {})
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Utility, Utility```
I will use this ticket to investigate/fix this error so that we can add the target field.

If this goes too far afield I'll pause this ticket and write a specific ticket for the above error

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-910?focusedCommentId=722853#comment-722853):_

Code changes in #1411

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-910?focusedCommentId=722853#comment-722853):_

Code changes in #1411
