### ISSUE TITLE
dark current subtraction output file fails

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#406]
_Issue [RCAL-285](https://jira.stsci.edu/browse/RCAL-285) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

When running the dark_current subtraction step with the optional --dark_output I see a failure with base path
```java
strun --verbose --dark_output="r0019101001023012008_darkoutput.asdf" romancal.step.DarkCurrentStep r0019101001023012008_01101_0173_WFI01_jumpstep.asdf
2022-01-06 13:58:37,231 - stpipe - DEBUG - Retrieving step PARS-DARKCURRENTSTEP parameters from CRDS
2022-01-06 13:58:37,435 - CRDS - ERROR - Error determining best reference for 'pars-darkcurrentstep' = Unknown reference type 'pars-darkcurrentstep'
2022-01-06 13:58:37,435 - stpipe - DEBUG - PARS-DARKCURRENTSTEP: No parameters found
2022-01-06 13:58:37,436 - stpipe.DarkCurrentStep - INFO - DarkCurrentStep instance created.
2022-01-06 13:58:37,462 - stpipe.DarkCurrentStep - INFO - Step DarkCurrentStep running with args ('r0019101001023012008_01101_0173_WFI01_jumpstep.asdf',).
2022-01-06 13:58:37,463 - stpipe.DarkCurrentStep - INFO - Step DarkCurrentStep parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.asdf', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'dark_output': '/Users/ddavis/src/Roman/develop/Dark/r0019101001023012008_darkoutput.asdf'}
2022-01-06 13:58:39,041 - stpipe.DarkCurrentStep - INFO - Using DARK reference file /Users/ddavis/crds_cache/references/roman/wfi/roman_wfi_dark_0117.asdf
----------------------------------------------------------------------
ERROR RUNNING STEP 'DarkCurrentStep':
 _make_output_path() got multiple values for argument 'basepath'
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/Users/ddavis/miniconda3/envs/rcal_dev/bin/strun", line 28, in <module>
 step = Step.from_cmdline(sys.argv[1:])
 File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.9/site-packages/stpipe/step.py", line 179, in from_cmdline
 return cmdline.step_from_cmdline(args)
 File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.9/site-packages/stpipe/cmdline.py", line 343, in step_from_cmdline
 step.run(*positional)
 File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.9/site-packages/stpipe/step.py", line 430, in run
 step_result = self.process(*args)
 File "/Users/ddavis/src/Roman/romancal/romancal/dark_current/dark_current_step.py", line 42, in process
 dark_output = self.make_output_path(
TypeError: _make_output_path() got multiple values for argument 'basepath'```

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-285?focusedCommentId=566585#comment-566585):_

Check if this is fixed by RAL-185 .

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-285?focusedCommentId=569718#comment-569718):_

This is fixed in RomanCAL PR-423: #423


This PR is not in review, yet, as it depends on PR-420.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-285?focusedCommentId=571233#comment-571233):_

Approved and merged.
