### ISSUE TITLE
Ramp Fit Multiprocessing IndexError

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#434]
_Issue [RCAL-309](https://jira.stsci.edu/browse/RCAL-309) was created on JIRA by [Tyler Desjardins](https://jira.stsci.edu/secure/ViewProfile.jspa?name=desjard):_

Executing the ramp fitting step with the following command:

`strun romancal.step.RampFitStep r0000101001001001001_01101_0001_WFI01_uncal_dqinitstep_saturationstep_linearitystep_darkcurrentstep_jumpstep.asdf --override_readnoise='cache/references/roman/wfi/test_readnoise.asdf' --maximum_cores='all'`

Produces the following:
2022-02-18 16:03:22,534 - stpipe.RampFitStep - INFO - RampFitStep instance created.
2022-02-18 16:03:22,572 - stpipe.RampFitStep - INFO - Step RampFitStep running with args ('r0000101001001001001_01101_0001_WFI01_uncal_dqinitstep_saturationstep_linearitystep_darkcurrentstep_jumpstep.asdf',).
2022-02-18 16:03:22,573 - stpipe.RampFitStep - INFO - Step RampFitStep parameters are: \{'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.asdf', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'opt_name': '', 'maximum_cores': 'all', 'save_opt': False}
2022-02-18 16:03:23,551 - stpipe.RampFitStep - INFO - Using READNOISE reference file: /Users/desjard/calibration/roman/gritdev/py_wfi_simulator/cache/references/roman/wfi/test_readnoise.asdf
2022-02-18 16:03:23,642 - stpipe.RampFitStep - INFO - Using GAIN reference file: ./cache/references/roman/wfi/roman_wfi_gain_0056.asdf
2022-02-18 16:03:23,663 - stpipe.RampFitStep - INFO - Using algorithm = ols
2022-02-18 16:03:23,663 - stpipe.RampFitStep - INFO - Using weighting = optimal
2022-02-18 16:03:23,727 - stpipe.RampFitStep - INFO - Number of processors used for multiprocessing: 16
----------------------------------------------------------------------
ERROR RUNNING STEP 'RampFitStep':
    too many indices for array: array is 3-dimensional, but 4 were
    indexed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/desjard/miniconda3/envs/rcaltest/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stpipe/step.py", line 179, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stpipe/cmdline.py", line 343, in step_from_cmdline
    step.run(*positional)
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stpipe/step.py", line 430, in run
    step_result = self.process(*args)
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/romancal/ramp_fitting/ramp_fit_step.py", line 134, in process
    image_info, integ_info, opt_info, gls_opt_model = ramp_fit.ramp_fit(
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stcal/ramp_fitting/ramp_fit.py", line 142, in ramp_fit
    return ramp_fit_data(
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stcal/ramp_fitting/ramp_fit.py", line 216, in ramp_fit_data
    image_info, integ_info, opt_info = ols_fit.ols_ramp_fit_multi(
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stcal/ramp_fitting/ols_fit.py", line 111, in ols_ramp_fit_multi
    image_info, integ_info, opt_info = ols_ramp_fit_multiprocessing(
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stcal/ramp_fitting/ols_fit.py", line 166, in ols_ramp_fit_multiprocessing
    slices, rows_per_slice = compute_slices_for_starmap(
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stcal/ramp_fitting/ols_fit.py", line 473, in compute_slices_for_starmap
    ramp_slice = slice_ramp_data(ramp_data, start_row, rslices[k])
  File "/Users/desjard/miniconda3/envs/rcaltest/lib/python3.9/site-packages/stcal/ramp_fitting/ols_fit.py", line 543, in slice_ramp_data
    err = ramp_data.err[:, :, start_row:start_row + nrows, :].copy()
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-309?focusedCommentId=572843#comment-572843):_

[Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) - don't forget to make sure this is traceable to a Saga

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Erica Kolatch](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ekolatch) on [JIRA](https://jira.stsci.edu/browse/RCAL-309?focusedCommentId=585998#comment-585998):_

[Tyler Desjardins](https://jira.stsci.edu/secure/ViewProfile.jspa?name=desjard); [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) - is this going to be resolved in build 0.6?

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/RCAL-309?focusedCommentId=586017#comment-586017):_

No, this is not going to be included in build 6. It is not going to be used in the pipeline, it's a user convenience.

Also changes to multiprocessing were made in stcal, as well as changes to data. We need to confirm first that this is still an issue.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-309?focusedCommentId=590114#comment-590114):_

I have found the error, resolved it, and written a test. However, in researching this (and another issue) a question about the shape of the error array has arisen, and so this is paused until that is resolved.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-309?focusedCommentId=593144#comment-593144):_

In implementing this ticket I needed to adjust the image model creation to match updated datamodels/schemas and I fixed the other ramp test and removed the pytest skip. I am adjusting the story points accordingly.

This is implemented in RCAL PR-523: #523

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Paul Huwe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=phuwe) on [JIRA](https://jira.stsci.edu/browse/RCAL-309?focusedCommentId=593419#comment-593419):_

PR approved and merged.
