### ISSUE TITLE
pytest failures from pyproject.toml updates?

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#789]
_Issue [RCAL-613](https://jira.stsci.edu/browse/RCAL-613) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

The roman_datamodels pytests are now failing.
```java
// /Users/ddavis/src/Roman/roman_datamodels
(rcal_dev) bash>pytest tests/
=============================================================== test session starts ================================================================
platform darwin -- Python 3.11.0, pytest-7.4.0, pluggy-1.2.0
rootdir: /Users/ddavis/src/Roman/roman_datamodels
configfile: pyproject.toml
plugins: remotedata-0.4.0, asdf-2.15.0, hypothesis-6.82.0, doctestplus-0.13.0, cov-4.1.0, filter-subpackage-0.1.2, mock-3.11.1, astropy-header-0.2.2, astropy-0.10.0, ci-watson-0.6.1, openfiles-0.5.0, arraydiff-0.5.0
collected 1115 items
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/pluggy/_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/pluggy/_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/pluggy/_callers.py", line 133, in _multicall
INTERNALERROR>     teardown[0].send(outcome)
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1346, in pytest_collection
INTERNALERROR>     self._validate_config_options()
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1373, in _validate_config_options
INTERNALERROR>     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1411, in _warn_or_fail_if_strict
INTERNALERROR>     self.issue_config_time_warning(PytestConfigWarning(message), stacklevel=3)
INTERNALERROR>   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1465, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: env============================================================== no tests ran in 1.19s```
This is using a fresh install,

conda create -n rcal_dev python==3.11

conda activate rcal_dev

pip install -e .[test,docs]



This appears to be from the pyproject.toml setup of

env = [
    "ROMAN_VALIDATE=true",
    "ROMAN_STRICT_VALIDATION=true",
]

The install procedure will need to be updated or these changes fixed.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [William Jamieson](https://jira.stsci.edu/secure/ViewProfile.jspa?name=wjamieson) on [JIRA](https://jira.stsci.edu/browse/RCAL-613?focusedCommentId=653816#comment-653816):_

This is essentially the same issue as what was reported in RCAL-563.

That is the `env` configuration is for the `pytest-env` plugin now being used by `roman_datamodels` for testing the `nuke_validation` configuration option. Notice that right now on the `main` branch of `roman_datamodels` that `pytest-env` is indeed a `[test]` dependency of `roman_datamodels` see <https://github.com/spacetelescope/roman_datamodels/blob/9a8dc3ab9cb7933e70ace4bd5b67c99fd64ce23c/pyproject.toml#L32];> moreover, it has been a `[test]` dependency of `roman_datamodels` since version `0.15.0` of `roman_datamodels`. Indeed, if this was a general issue one would expect this type of problem to [498a84e](https://github.com/spacetelescope/roman_datamodels/commit/498a84e615dd2ed7430cf6aaeedb88bdf06868ec), but no such failures can be found by reviewing the existing GitHub [CI logs](https://github.com/spacetelescope/roman_datamodels/actions/workflows/ci.yml).

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Zach Burnett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=zburnett) on [JIRA](https://jira.stsci.edu/browse/RCAL-613?focusedCommentId=653893#comment-653893):_

it appears the issue was typing `pip install -e .[tests]` instead of `pip install -e .[test]`; added instructions to the README to reduce this typo in the future
