### ISSUE TITLE
Update ModelContainer for use with Context manager

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#812]
_Issue [RCAL-620](https://jira.stsci.edu/browse/RCAL-620) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

The ModelContainer currently fails when used with the context manager with
```java
Traceback (most recent call last):
  File "/Users/ddavis/miniconda3/envs/rcal_dev/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/stpipe/step.py", line 186, in from_cmdline
    return cmdline.step_from_cmdline(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/stpipe/cmdline.py", line 375, in step_from_cmdline
    step, step_class, positional, debug_on_exception = just_the_step_from_cmdline(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/stpipe/cmdline.py", line 308, in just_the_step_from_cmdline
    parameter_cfg = step_class.get_config_from_reference(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/stpipe/pipeline.py", line 182, in get_config_from_reference
    with cls._datamodels_open(dataset, asn_n_members=1) as model:
TypeError: 'ModelContainer' object does not support the context manager protocol```
and I think it needs the methods ``
```java
__enter__```
`` and ``
```java
__exit__```
`{}{`}for use with the context manager.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-620?focusedCommentId=687955#comment-687955):_

Code to demonstrate the problem

 
```java
from romancal.datamodels import ModelContainer
input_file = 'L3_regtest_asn.json'
with ModelContainer(input_file) as asn1:
    print(asn1[0].meta.filename)
```
Fails with
```java
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'ModelContainer' object does not support the context manager protocol```
while
```java
asn2 = ModelContainer(input_file)
print(asn2[0].meta.filename)
r0000101001001001001_01101_0001_WFI01_cal.asdf```
works as expected.

**Comment by stscijgbot-rstdms** [comment]
_Comment by [Mairan Teodoro](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mteodoro) on [JIRA](https://jira.stsci.edu/browse/RCAL-620?focusedCommentId=689241#comment-689241):_

PR for review: #1147
