### ISSUE TITLE
Pipeline processing using an association (fix)

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#852]
_Issue [RCAL-642](https://jira.stsci.edu/browse/RCAL-642) was created on JIRA by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis):_

Using an input association for the ELPP processing seems to be broken at the moment.

Using the original input association and files produces an error,
```java
strun  --debug roman_elp r90001-a3001_image_001_asn.json Traceback (most recent call last):   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/roman_datamodels/datamodels/_utils.py", line 52, in _open_path_like     asdf_file = asdf.open(init, **kwargs)                 ^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/asdf/asdf.py", line 1938, in open_asdf     return AsdfFile._open_impl(            ^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/asdf/asdf.py", line 978, in _open_impl     return cls._open_generic_file(            ^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/asdf/asdf.py", line 1060, in _open_generic_file     raise ValueError(msg) ValueError: Input object does not appear to be an ASDF file or a FITS with ASDF extensionThe above exception was the direct cause of the following exception:Traceback (most recent call last):   File "/Users/ddavis/miniconda3/envs/rcal_dev/bin/strun", line 26, in <module>     step = Step.from_cmdline(sys.argv[1:])            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/stpipe/step.py", line 186, in from_cmdline     return cmdline.step_from_cmdline(args)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/stpipe/cmdline.py", line 375, in step_from_cmdline     step, step_class, positional, debug_on_exception = just_the_step_from_cmdline(                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/stpipe/cmdline.py", line 308, in just_the_step_from_cmdline     parameter_cfg = step_class.get_config_from_reference(                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/stpipe/pipeline.py", line 182, in get_config_from_reference     with cls._datamodels_open(dataset, asn_n_members=1) as model:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/src/Roman/romancal/romancal/stpipe/core.py", line 41, in _datamodels_open     return rdm.open(init, **kwargs)            ^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/roman_datamodels/datamodels/_utils.py", line 93, in rdm_open     asdf_file = init if isinstance(init, asdf.AsdfFile) else _open_path_like(init, memmap=memmap, **kwargs)                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/roman_datamodels/datamodels/_utils.py", line 54, in _open_path_like     raise TypeError("Open requires a filepath, file-like object, or Roman datamodel") from err TypeError: Open requires a filepath, file-like object, or Roman datamodel```

**Comment by stscijgbot-rstdms** [comment]
_Comment by [David Davis](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ddavis) on [JIRA](https://jira.stsci.edu/browse/RCAL-642?focusedCommentId=676825#comment-676825):_

strun roman_elp test_asn.json now runs through tweakreg,

 
```java
>strun roman_elp test_asn.json
2023-12-19 08:20:49,088 - stpipe - WARNING - **WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-062 CANNOT BE CHECKED AGAINST ONLINE VERSION
2023-12-19 08:20:49,166 - stpipe.ExposurePipeline - INFO - ExposurePipeline instance created.
2023-12-19 08:20:49,167 - stpipe.ExposurePipeline.dq_init - INFO - DQInitStep instance created.
2023-12-19 08:20:49,167 - stpipe.ExposurePipeline.saturation - INFO - SaturationStep instance created.
2023-12-19 08:20:49,168 - stpipe.ExposurePipeline.refpix - INFO - RefPixStep instance created.
2023-12-19 08:20:49,169 - stpipe.ExposurePipeline.linearity - INFO - LinearityStep instance created.
2023-12-19 08:20:49,169 - stpipe.ExposurePipeline.dark_current - INFO - DarkCurrentStep instance created.
2023-12-19 08:20:49,170 - stpipe.ExposurePipeline.rampfit - INFO - RampFitStep instance created.
2023-12-19 08:20:49,171 - stpipe.ExposurePipeline.assign_wcs - INFO - AssignWcsStep instance created.
2023-12-19 08:20:49,171 - stpipe.ExposurePipeline.flatfield - INFO - FlatFieldStep instance created.
2023-12-19 08:20:49,172 - stpipe.ExposurePipeline.photom - INFO - PhotomStep instance created.
2023-12-19 08:20:49,173 - stpipe.ExposurePipeline.source_detection - INFO - SourceDetectionStep instance created.
2023-12-19 08:20:49,174 - stpipe.ExposurePipeline.tweakreg - INFO - TweakRegStep instance created.
2023-12-19 08:20:49,174 - stpipe - INFO - Hostname: attilla.local.stsci.edu
...
2023-12-19 08:24:02,313 - stpipe.ExposurePipeline.tweakreg - INFO - Selected image 'GROUP ID: r0000101001001001001_01101_0001_WFI01_cal' as reference image
2023-12-19 08:24:02,325 - stpipe.ExposurePipeline.tweakreg - INFO - Aligning image catalog 'GROUP ID: r0000101001001001001_01101_0002_WFI01_cal' to the reference catalog.
----------------------------------------------------------------------
ERROR RUNNING STEP 'ExposurePipeline':
    cannot pickle 'dict_keys' object
----------------------------------------------------------------------```
  The error seems to be coming from,
```java
File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/tweakwcs/imalign.py", line 683, in align_wcs
    current_wcat.align_to_ref(
  File "/Users/ddavis/miniconda3/envs/rcal_dev/lib/python3.11/site-packages/tweakwcs/wcsimage.py", line 1343, in align_to_ref
    ref_tpwcs = deepcopy(self._images[0].corrector)```
Which is a step specific issue, closing this issue.
